# Handling Date Time

In [1]:
import pandas as pd 
import numpy as np

In [2]:
date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [4]:
date.sample(10),time.sample(10)

(           date  product_id  city_id  orders
 552  2019-02-04        5955       16       3
 910  2019-04-25        2504        2       2
 153  2019-01-13        4576       22       1
 772  2018-11-05        6845       13       3
 329  2019-03-05        5347        3       5
 102  2018-08-30        3328       29       1
 268  2018-11-14        6642        4       1
 696  2019-03-19        6065       18       2
 853  2019-08-11        7430        1       1
 204  2018-10-07         820       30       2,
                     date                                                msg
 448  2014-11-09 00:19:00  Милые Красавицы мне скучно ну проста пипец зво...
 559  2013-05-13 00:44:00  голова не болит   готовить умею   футбол люблю...
 74   2012-10-28 00:04:00  П28 ищу девушку до 35 можно в теле из дн-жинск...
 693  2015-03-03 00:04:00       парню скучно 20 лет днепр звоните 0935679735
 658  2014-09-23 01:05:00  Приятно  когда рядом любимый человек... Но его...
 921  2014-04-28 23:59:00             .м+м.новомосковск.34.170.17.0930593188
 594  2015-03-24 23:50:00                       хочу Д/Ж по с м с 0979168706
 944  2015-05-21 23:11:00  П 27/184/90 ищу дев 18-30 лет для с/с совм про...
 43   2013-11-16 23:46:00        Вы лучшие! нашел Девушку она делает всееее!
 7    2012-11-23 01:10:00                  ДЛЯ С.П СНАЧАЛО СМС 066.679.400.8)

In [6]:
date["date"]=pd.to_datetime(date["date"])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [7]:
date["date_year"]=date["date"].dt.year

In [15]:
date["date_month"]=date["date"].dt.month
date["date_month_name"]=date["date"].dt.month_name()
date["date_day"]=date["date"].dt.day
date["date_dow"]=date["date"].dt.day_of_week
date["date_now"]=date["date"].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_dow,date_now
328,2019-11-20,7467,23,2,2019,11,20,November,2,Wednesday
377,2019-01-25,2876,1,1,2019,1,25,January,4,Friday
401,2018-12-31,7508,16,5,2018,12,31,December,0,Monday
749,2019-05-31,4984,25,3,2019,5,31,May,4,Friday
733,2019-07-10,3081,30,5,2019,7,10,July,2,Wednesday

In [16]:
date["is_weekend"]= np.where(date["date_now"].isin(["Saturday","Sunday"]),1,0)

In [17]:
date.sample(10)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_dow,date_now,is_weekend
222,2019-01-22,5002,13,15,2019,1,22,January,1,Tuesday,0
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday,0
665,2018-09-29,146,16,5,2018,9,29,September,5,Saturday,1
881,2019-07-14,2897,26,6,2019,7,14,July,6,Sunday,1
77,2018-11-02,5905,30,1,2018,11,2,November,4,Friday,0
837,2018-12-15,5407,13,68,2018,12,15,December,5,Saturday,1
198,2018-08-28,685,25,29,2018,8,28,August,1,Tuesday,0
328,2019-11-20,7467,23,2,2019,11,20,November,2,Wednesday,0
247,2019-12-06,7148,16,29,2019,12,6,December,4,Friday,0
333,2019-10-31,1494,25,71,2019,10,31,October,3,Thursday,0

In [18]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [20]:
time["date"]=pd.to_datetime(time["date"])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [23]:
time["hour"]=time["date"].dt.hour
time["min"]=time["date"].dt.minute
time["sec"]=time["date"].dt.second
time["time"]=time["date"].dt.time
time.sample(10)

,date,msg,hour,min,sec,time
311,2012-02-19 23:18:00,хочу поговор.с симп.парн.0935044828,23,18,0,23:18:00
328,2014-11-01 23:05:00,Реально хочу дев.женщ.сейчас не стесняйтесь! 0...,23,5,0,23:05:00
878,2015-08-14 23:10:00,. Сделаю Девушке приятно от 30. Днепр.097 137 ...,23,10,0,23:10:00
880,2013-04-23 00:56:00,всем привет парни пишите а то скучно!,0,56,0,00:56:00
219,2014-04-20 01:03:00,ХРИСТОС ВОСКРЕС Х- 23 КОМПОТУ! модер поставь г...,1,3,0,01:03:00
139,2012-10-16 01:51:00,парень 25 из Днепра ищет девчонку для встреч 0...,1,51,0,01:51:00
977,2013-08-21 23:33:00,МУЖЧИНА 40 ПОЗНАКОМЛЮСЬ С СЕМЕЙНОЙ ПАРОЙ 09339...,23,33,0,23:33:00
607,2016-04-18 23:44:00,Приятный мужчина пригласит в гости пару МЖ. Дл...,23,44,0,23:44:00
508,2015-09-28 22:47:00,поцелую женщине...0666608116,22,47,0,22:47:00
701,2014-08-22 00:53:00,Я САША МНЕ 29СВЕТЛОГЛАЗЫЙ.0951979497,0,53,0,00:53:00