In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

# KNN Imputer

In [ ]:
df = pd.read_csv( "../../understanding-data/train.csv", usecols=["Age","Fare", "Survived","Pclass"] )

In [3]:
df.isnull().mean()

Survived    0.000000
Pclass      0.000000
Age         0.198653
Fare        0.000000
dtype: float64

In [4]:
x = df.drop(columns=["Survived"])
y=df["Survived"]

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [6]:
knn=KNNImputer(add_indicator=True,n_neighbors=3)
x_train_trf=knn.fit_transform(x_train)
x_test_trf = knn.fit_transform(x_test)
x_train.sample()

/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:557: RuntimeWarning: divide by zero encountered in dot
  distances -= np.dot(XX, missing_Y.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:557: RuntimeWarning: overflow encountered in dot
  distances -= np.dot(XX, missing_Y.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:557: RuntimeWarning: invalid value encountered in dot
  distances -= np.dot(XX, missing_Y.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:558: RuntimeWarning: divide by zero encountered in dot
  distances -= np.dot(missing_X, YY.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:558: RuntimeWarning: overflow encountered in dot
  distances -= np.dot(missing_X, YY.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:558: RuntimeWarning: invalid value encountered in dot
  distances -= np.dot(missing_X, YY.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:557: RuntimeWarning: divide by zero encountered in dot
  distances -= np.dot(XX, missing_Y.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:557: RuntimeWarning: overflow encountered in dot
  distances -= np.dot(XX, missing_Y.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:557: RuntimeWarning: invalid value encountered in dot
  distances -= np.dot(XX, missing_Y.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:558: RuntimeWarning: divide by zero encountered in dot
  distances -= np.dot(missing_X, YY.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:558: RuntimeWarning: overflow encountered in dot
  distances -= np.dot(missing_X, YY.T)
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/metrics/pairwise.py:558: RuntimeWarning: invalid value encountered in dot
  distances -= np.dot(missing_X, YY.T)

     Pclass   Age   Fare
664       3  20.0  7.925

In [8]:
pd.DataFrame(x_train_trf, columns=["Pclass","Age","Fare","age_na"]).sample(10)

     Pclass        Age     Fare  age_na
121     1.0  42.333333  51.8625     1.0
335     2.0  50.000000  26.0000     0.0
501     2.0  24.000000  10.5000     0.0
275     2.0  23.000000  15.0458     0.0
315     3.0  10.000000  24.1500     0.0
555     3.0  30.000000   9.5000     0.0
159     1.0  60.000000  75.2500     0.0
540     2.0  22.000000  29.0000     0.0
89      1.0  51.000000  26.5500     0.0
149     3.0  11.000000  18.7875     0.0

In [9]:
lr=LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred = lr.predict(x_test_trf)

accuracy_score(y_pred,y_test)

/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/keshavmacbook/Projects/AI-ML/AI-ML basic/.aiml-venv/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept

0.7374301675977654